### ISSUE TITLE
ASDF/PLANS:SYSTEM-OUT-OF-DATE when using with cl-dbi

### ISSUE THREAD

**Issue by diasbruno** [fukamachi/anypool#7]
I've recently added anypool to a project, and, I got this message `ASDF/PLANS:SYSTEM-OUT-OF-DATE` whenever I tried to fetch a connection. 

Project setup:

- Docker
- Running clack+woo from the command line `clack --server woo [options] app.lisp`

I thought this error was related to some lazy loading of the `dbd-postgres` package, but it should stop raising this exception after the package was loaded (?). Unfortunately, this is not the case.

As a "workaround", I had to load the dbd-postgres before the application started.

Running locally it doesn't raise the exception, but I need to do other tests.

I'l post more information about the environment.

Docker image: fukamachi/sbcl:2.3.9-debian fukamachi/sbcl:2.4.1-debian
sbcl: 2.3.9, 2.4.3
packages: cl-dbi 0.9.5
                   asdf 3.3.1

**Comment by fukamachi** [comment]
As you pointed out, CL-DBI automatically loads a driver if it's not yet.
To stop the behavior, load dbd-postgres in advance. This is not a workaround but a proper solution.

**Comment by diasbruno** [comment]
Great. Thought there was a trick. Thanks, @fukamachi.
